{
 "title": "z/OS Usage by Job",
 "tags": [ "RMF" ],
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "Sysplex",
    "query": {
     "query": "label_values(mvs_rmf_m3_mintime,sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   },
   {
    "name": "sysname",
    "label": "Sysname",
    "query": {
     "query": "label_values(mvs_wlm_group_delay_percent{sysplex=~\"$sysplex\"},sysname)"
    }
   },
   {
    "name": "jobname",
    "label": "Jobname",
    "query": {
     "query": "label_values(mvs_job_total_eappl_percent{sysplex=~\"$sysplex\", sysname=~\"$sysname\"},job_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current CP Usage (Top 20)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, mvs_job_total_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"})",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "Current Working Sets (Top 20)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, mvs_job_working_set_frames_total{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"} * 4096)",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "Current GCP Usage (Top 20)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, mvs_job_cp_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"})",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "Current ZIIP Usage (Top 20)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, mvs_job_iip_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"})",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  { "title": "Usage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total CP Usage by Job (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_job_total_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\",job_name=~\"${jobname}\"}",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "Working Sets by Job (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mvs_job_working_set_frames_total{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\",job_name=~\"${jobname}\"} * 4096",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "GCP Usage by Job (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_job_cp_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\",job_name=~\"${jobname}\"}",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "ZIIP Usage by Job (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_job_iip_eappl_percent{sysplex=~\"${sysplex}\",sysname=~\"${sysname}\",job_name=~\"${jobname}\"}",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  }
 ]
}