{
 "title": "z/OS MSU Capacity",
 "tags": [ "RMF" ],
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cpcId",
    "label": "CPC ID",
    "query": {
     "query": "label_values(mvs_cpc_capacity_msu_h,cpc_id)"
    }
   },
   {
    "name": "sysplex",
    "query": {
     "query": "label_values(mvs_cpc_capacity_msu_h{cpc_id=~\"$cpcId\"},sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current CPC Capacity (percent)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cpc_id) (mvs_lpar_actual_msu_h{line_type=\"CP\",cpc_id=~\"${cpcId}\"}) / on(cpc_id) sum by(cpc_id) (mvs_cpc_capacity_msu_h{cpc_id=~\"${cpcId}\"})",
     "legendFormat": "{{cpc_sequence_number}}"
    }
   ]
  },
  {
   "title": "Current LPAR Capacity (MSU / hour)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Use average values since the same CPC info may come from different sysplexes\nsort_desc(avg by (cpc_id, lpar_name) (mvs_lpar_actual_msu_h{line_type=\"CP\", cpc_id=~\"${cpcId}\"}))",
     "legendFormat": "{{cpc_id}}.{{lpar_name}}"
    }
   ]
  },
  { "title": "Usage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPC Capacity (percent)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cpc_id) (mvs_lpar_actual_msu_h{line_type=\"CP\",cpc_id=~\"${cpcId}\"}) / on(cpc_id) sum by(cpc_id) (mvs_cpc_capacity_msu_h{cpc_id=~\"${cpcId}\"})",
     "legendFormat": "{{cpc_id}}"
    }
   ]
  },
  {
   "title": "Actual LPAR Capacity (MSU / hour)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "# Use average values since the same CPC info may come from different sysplexes\navg by (cpc_id, lpar_name) (mvs_lpar_actual_msu_h{line_type=\"CP\", cpc_id=~\"${cpcId}\"})",
     "legendFormat": "{{cpc_id}}.{{lpar_name}}"
    }
   ]
  }
 ]
}