{
 "title": "z/OS Central Storage Usage",
 "tags": [ "RMF" ],
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "Sysplex",
    "query": {
     "query": "label_values(mvs_rmf_m3_mintime,sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Central Storage by System",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"} * 4096,\n    \"__name__\",\n    \"Storage Online\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "{{sysname}}"
    },
    {
     "expr": "label_replace(\n    mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"} * 4096,\n    \"__name__\",\n    \"Storage Available\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"} / mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"},\n    \"__name__\",\n    \"Storage Available (%)\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    (mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"} - mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"}) * 4096,\n    \"__name__\",\n    \"Storage Used\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    1 - mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"} / mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"},\n    \"__name__\",\n    \"Storage Used (%)\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Usage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Central Storage Usage by System (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"} - mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"}) * 4096",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "Central Storage Usage by System (percent)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - mvs_system_storage_frames_available_total{sysplex=~\"${sysplex}\"} / mvs_system_storage_real_storage_frames{sysplex=~\"${sysplex}\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  }
 ]
}