{
 "title": "z/OS Common Storage Usage",
 "tags": [ "RMF" ],
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "Sysplex",
    "query": {
     "query": "label_values(mvs_rmf_m3_mintime,sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CSA Usage by System (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_system_storage_csa_average_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "SQA Usage by System (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_system_storage_sqa_average_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "ECSA Usage by System (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_system_storage_ecsa_average_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "ESQA Usage by System (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_system_storage_esqa_average_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "CSA Usage by Job (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_job_storage_csa_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  {
   "title": "SQA Usage by Job (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_job_storage_sqa_percent{sysplex=~\"${sysplex}\"})",
     "legendFormat": "{{sysname}}.{{job_name}} [{{asid_dec}}]"
    }
   ]
  },
  { "title": "Usage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CSA Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_system_storage_csa_average_percent{sysplex=~\"${sysplex}\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "SQA Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_system_storage_sqa_average_percent{sysplex=~\"${sysplex}\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "ECSA Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_system_storage_ecsa_average_percent{sysplex=~\"${sysplex}\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  },
  {
   "title": "ESQA Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_system_storage_esqa_average_percent{sysplex=~\"${sysplex}\"}",
     "legendFormat": "{{sysname}}"
    }
   ]
  }
 ]
}