{
 "title": "z/OS WLM Workload Delays",
 "tags": [ "RMF" ],
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "Sysplex",
    "query": {
     "query": "label_values(mvs_rmf_m3_mintime,sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   },
   {
    "name": "sysname",
    "label": "Sysname",
    "query": {
     "query": "label_values(mvs_wlm_group_delay_percent{sysplex=~\"$sysplex\"},sysname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current WLM Workload Delays by Type (Top 20)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, label_replace({__name__=~\"mvs_wlm_group_delay_(.*)_percent\", group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}, \"delay\", \"$1\", \"__name__\", \"mvs_wlm_group_delay_(.*)_percent\"))",
     "legendFormat": "{{sysname}}.{{group_name}} ({{delay}})"
    }
   ]
  },
  {
   "title": "Average WLM Workload Delays",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Total Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_proc_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Processor Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_oper_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Operator Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_jes_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"JES Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_hsm_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"HSM Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_dev_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Device Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_enq_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Enqueue Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_stor_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Storage Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_subs_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"Subsystem Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n    avg_over_time(mvs_wlm_group_delay_xcf_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}[$__range]),\n    \"__name__\",\n    \"XCF Delay\",\n    \"\",\n    \".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WLM Workload Total Delays",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_wlm_group_delay_percent{group_type=\"W\",sysplex=~\"${sysplex}\",sysname=~\"${sysname}\"}",
     "legendFormat": "{{sysname}}.{{group_name}}"
    }
   ]
  }
 ]
}