{
 "title": "z/OS Coupling Facility Usage",
 "tags": [ "RMF" ],
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "Sysplex",
    "query": {
     "query": "label_values(mvs_rmf_m3_mintime,sysplex)"
    }
   },
   {
    "name": "mintime",
    "query": {
     "query": "query_result(max(mvs_rmf_m3_mintime{sysplex=~\"${sysplex}\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processor Usage by Coupling Facility (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_cf_processor_utilization_percent)",
     "legendFormat": "{{sysplex}}.{{name}}"
    }
   ]
  },
  {
   "title": "Coupling Facility Request Rate (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, mvs_cf_request_rate)", "legendFormat": "{{sysplex}}.{{name}}" }
   ]
  },
  {
   "title": "Storage Usage by Coupling Facility (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mvs_cf_storage_utilized_percent)",
     "legendFormat": "{{sysplex}}.{{name}}"
    }
   ]
  },
  { "title": "Usage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Processor Usage by Coupling Facility",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_cf_processor_utilization_percent",
     "legendFormat": "{{sysplex}}.{{name}}"
    }
   ]
  },
  {
   "title": "Coupling Facility Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "mvs_cf_request_rate", "legendFormat": "{{sysplex}}.{{name}}" }
   ]
  },
  {
   "title": "Storage Usage by Coupling Facility (bytes) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mvs_cf_storage_size_bytes - mvs_cf_storage_available_bytes",
     "legendFormat": "{{sysplex}}.{{name}}"
    }
   ]
  },
  {
   "title": "Storage Usage by Coupling Facility (percent) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mvs_cf_storage_utilized_percent",
     "legendFormat": "{{sysplex}}.{{name}}"
    }
   ]
  }
 ]
}